module.exports = () => ({
  backgroundColor: '#FFFFFF',
  colors: [
    '#FFC18C',
    '#CEFB74',
    '#82FBB6',
    '#7CC7FF',
    '#C17DFF',
    '#FF7FD8',
    '#FFC18C',
  ],
  dashSize: 1,
  dashSpaceSize: 0,
  discreteColors: false,
  height: 400,
  lineWidth: 4,
  numLines: 15,
  ratioUpFirst: 0.5,
  seed: 1,
  startVariance: 0.7,
  width: 700,
  xVariance: 0.1,
  yVariance: 0.5,
})
